# Generated by Django 4.2 on 2023-06-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("post_title", models.CharField(max_length=50)),
                ("post_date", models.DateTimeField()),
                ("post_text", models.TextField()),
            ],
            options={
                "db_table": "post",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("video_id", models.AutoField(primary_key=True, serialize=False)),
                ("video_title", models.CharField(max_length=30)),
                ("video_addr", models.CharField(max_length=50)),
                ("upload_date", models.DateTimeField()),
            ],
            options={
                "db_table": "video",
                "managed": False,
            },
        ),
    ]
