# Generated by Django 4.2 on 2023-06-26 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_delete_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
