# Generated by Django 4.2 on 2023-06-27 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
